### ISSUE TITLE
proxy_url definition needs quotes to recognize  'None' as a value 

### ISSUE THREAD

**Issue by mcbrown87** [christian-schlichtherle/kalaxy#1]
When trying to execute the playbook, it was applying the proxy url even though it was set to 'None'. I fixed it by adding quotes around all of the 'None' values.

**Comment by christian-schlichtherle** [comment]
Do you mind sending a pull request?

**Comment by mcbrown87** [comment]
I have the change in a local branch and it looks like I don't have permission to push to a remote branch

**Comment by christian-schlichtherle** [comment]
You need to clone the project, push your changes to your clone and then open a pull request.

**Comment by christian-schlichtherle** [comment]
I think this is caused by YAML parsing `None` as a string. I've replaced these defaults with `null` so that Python can translate it to `None`. This fix is included in version 0.6.7. Let me know if it works for you.
